-- 内置模板占位符全量默认数据（与 TemplateController 五套模板、init-defaults API 一致）
-- 新增变量插入；已有 code 则更新名称、英文、标签、类型、分类、说明、排序

INSERT INTO template_variable (code, name, name_en, label, type, category, description, required, sort_order, status) VALUES
('contractNo', '合同编号', 'Contract Number', '合同编号', 'text', 'system', '自动生成的合同编号', 0, 1, 1),
('title', '合同名称', 'Contract Title', '合同名称', 'text', 'system', '合同的标题', 0, 2, 1),
('amount', '合同金额', 'Contract Amount', '合同金额', 'number', 'system', '合同总金额', 0, 3, 1),
('amountChinese', '金额大写', 'Amount in Words', '金额大写', 'text', 'system', '金额中文大写', 0, 4, 1),
('startDate', '开始日期', 'Start Date', '起始日期', 'date', 'system', '合同开始/起始日期', 0, 5, 1),
('endDate', '结束日期', 'End Date', '结束日期', 'date', 'system', '合同结束日期', 0, 6, 1),
('signDate', '签订日期', 'Signing Date', '签订日期', 'date', 'system', '合同签订日期', 0, 7, 1),
('today', '当前日期', 'Today''s Date', '当前日期', 'text', 'system', '当前日期', 0, 8, 1),
('partyA', '甲方名称', 'Party A Name', '甲方公司名称', 'text', 'party', '甲方公司全称', 0, 10, 1),
('partyB', '乙方名称', 'Party B Name', '乙方公司名称', 'text', 'party', '乙方公司全称', 0, 11, 1),
('partyAId', '甲方证件号', 'Party A ID Number', '甲方证件号码', 'text', 'party', '甲方身份证明号码', 0, 12, 1),
('partyBId', '乙方证件号', 'Party B ID Number', '乙方证件号码', 'text', 'party', '乙方身份证明号码', 0, 13, 1),
('partyAContact', '甲方联系人', 'Party A Contact', '甲方联系人', 'text', 'party', '甲方联系人姓名', 0, 14, 1),
('partyAPhone', '甲方电话', 'Party A Phone', '甲方联系电话', 'text', 'party', '甲方联系电话', 0, 15, 1),
('partyAEmail', '甲方邮箱', 'Party A Email', '甲方邮箱', 'text', 'party', '甲方电子邮箱', 0, 16, 1),
('partyAAddress', '甲方地址', 'Party A Address', '甲方地址', 'text', 'party', '甲方公司地址', 0, 17, 1),
('partyBContact', '乙方联系人', 'Party B Contact', '乙方联系人', 'text', 'party', '乙方联系人姓名', 0, 18, 1),
('partyBPhone', '乙方电话', 'Party B Phone', '乙方联系电话', 'text', 'party', '乙方联系电话', 0, 19, 1),
('partyBEmail', '乙方邮箱', 'Party B Email', '乙方邮箱', 'text', 'party', '乙方电子邮箱', 0, 20, 1),
('partyBAddress', '乙方地址', 'Party B Address', '乙方地址', 'text', 'party', '乙方公司地址', 0, 21, 1),
('partyASign', '甲方签章', 'Party A Signature', '甲方签章', 'text', 'party', '甲方签章栏', 0, 22, 1),
('partyBSign', '乙方签章', 'Party B Signature', '乙方签章', 'text', 'party', '乙方签章栏', 0, 23, 1),
('productName', '产品名称', 'Product Name', '产品名称', 'text', 'purchase', '采购/代理产品名称', 0, 30, 1),
('quantity', '数量', 'Quantity', '数量', 'number', 'purchase', '采购数量', 0, 31, 1),
('unitPrice', '单价', 'Unit Price', '单价', 'number', 'purchase', '产品单价', 0, 32, 1),
('totalPrice', '总价', 'Total Price', '总价', 'number', 'purchase', '产品总价', 0, 33, 1),
('deliveryDays', '交货天数', 'Delivery Days', '交货天数', 'number', 'purchase', '交货期限（天）', 0, 34, 1),
('deliveryAddress', '交货地址', 'Delivery Address', '交货地址', 'text', 'purchase', '交货/收货详细地址（与表单 delivery_address 对齐）', 0, 35, 1),
('paymentDays', '付款天数', 'Payment Days', '付款周期', 'number', 'purchase', '付款期限（天）', 0, 36, 1),
('penaltyRate', '违约金比例', 'Penalty Rate (%)', '违约金比例', 'number', 'purchase', '违约金百分比', 0, 37, 1),
('projectName', '项目名称', 'Project Name', '项目名称', 'text', 'service', '服务项目名称', 0, 40, 1),
('projectDesc', '项目描述', 'Project Description', '项目描述', 'textarea', 'service', '项目详细描述', 0, 41, 1),
('deliverables', '交付成果', 'Deliverables', '交付成果', 'textarea', 'service', '交付成果物', 0, 42, 1),
('totalDays', '总工期', 'Total Duration (Days)', '总工期', 'number', 'service', '项目总工期（工作日）', 0, 43, 1),
('totalAmount', '合同总金额', 'Total Contract Amount', '合同总金额', 'number', 'service', '服务合同总金额（数字）', 0, 44, 1),
('totalAmountChinese', '合同总金额(大写)', 'Total Amount (Chinese)', '合同总金额大写', 'text', 'service', '服务合同总金额中文大写', 0, 45, 1),
('firstPayment', '首付款', 'Down Payment', '首付款', 'number', 'service', '首付款金额', 0, 46, 1),
('progressPayment', '进度款', 'Progress Payment', '进度款', 'number', 'service', '进度款金额', 0, 47, 1),
('finalPayment', '尾款', 'Final Payment', '尾款', 'number', 'service', '尾款金额', 0, 48, 1),
('address', '房屋地址', 'Property Address', '房屋地址', 'text', 'lease', '租赁房屋地址', 0, 50, 1),
('area', '建筑面积', 'Floor Area (sqm)', '建筑面积', 'number', 'lease', '建筑面积（平方米）', 0, 51, 1),
('leaseMonths', '租赁月数', 'Lease Term (Months)', '租赁月数', 'number', 'lease', '租赁期限（月）', 0, 52, 1),
('monthlyRent', '月租金', 'Monthly Rent', '月租金', 'number', 'lease', '每月租金', 0, 53, 1),
('monthlyRentChinese', '月租金(大写)', 'Monthly Rent (Chinese)', '月租金大写', 'text', 'lease', '月租金中文大写', 0, 54, 1),
('deposit', '押金', 'Security Deposit', '押金', 'number', 'lease', '租赁押金', 0, 55, 1),
('depositChinese', '押金(大写)', 'Deposit (Chinese)', '押金大写', 'text', 'lease', '押金中文大写', 0, 56, 1),
('noticeDays', '提前通知天数', 'Notice Period (Days)', '提前通知天数', 'number', 'lease', '提前解约书面通知天数', 0, 57, 1),
('penaltyMonths', '违约金月数', 'Penalty (Months of Rent)', '违约金月数', 'number', 'lease', '提前解约违约金（月租金倍数）', 0, 58, 1),
('companyName', '公司名称', 'Company Name', '公司名称', 'text', 'employment', '用人单位名称', 0, 60, 1),
('employeeName', '员工姓名', 'Employee Name', '员工姓名', 'text', 'employment', '劳动者姓名', 0, 61, 1),
('employeeId', '身份证号', 'ID Number', '身份证号', 'text', 'employment', '劳动者身份证号码', 0, 62, 1),
('employeePhone', '联系电话', 'Phone Number', '联系电话', 'text', 'employment', '劳动者联系电话', 0, 63, 1),
('position', '职位', 'Position', '岗位/职位', 'text', 'employment', '工作岗位', 0, 64, 1),
('workContent', '工作内容', 'Job Duties', '工作内容', 'textarea', 'employment', '工作内容描述', 0, 65, 1),
('workLocation', '工作地点', 'Work Location', '工作地点', 'text', 'employment', '工作地点', 0, 66, 1),
('salary', '月薪(通用)', 'Monthly Salary (Generic)', '月薪', 'number', 'employment', '通用月薪（可与月工资字段并存）', 0, 67, 1),
('monthlySalary', '月工资', 'Monthly Salary', '月工资', 'number', 'employment', '劳动合同月工资', 0, 68, 1),
('monthlySalaryChinese', '月工资(大写)', 'Monthly Salary (Chinese)', '月工资大写', 'text', 'employment', '月工资中文大写', 0, 69, 1),
('payDay', '工资发放日', 'Pay Day', '工资发放日', 'number', 'employment', '每月发薪日（日）', 0, 70, 1),
('probationPeriod', '试用期', 'Probation Period (Months)', '试用期', 'number', 'employment', '试用期（月）', 0, 71, 1),
('nonCompeteMonths', '竞业限制月数', 'Non-compete Period (Months)', '竞业限制月数', 'number', 'employment', '竞业限制期限（月）', 0, 72, 1),
('nonCompeteCompensation', '竞业限制补偿金', 'Non-compete Compensation', '竞业限制补偿金', 'number', 'employment', '竞业限制补偿（元/月）', 0, 73, 1),
('companySign', '用人单位签章', 'Company Signature', '公司签章', 'text', 'employment', '用人单位签章栏', 0, 74, 1),
('employeeSign', '员工签章', 'Employee Signature', '员工签章', 'text', 'employment', '劳动者签章栏', 0, 75, 1),
('brand', '品牌', 'Brand', '品牌', 'text', 'agency', '代理产品品牌', 0, 80, 1),
('specification', '型号规格', 'Model / Specification', '型号规格', 'text', 'agency', '产品型号规格', 0, 81, 1),
('region', '代理区域', 'Territory', '代理区域', 'text', 'agency', '销售代理区域', 0, 82, 1),
('annualTask', '年度销售任务', 'Annual Sales Target', '年度销售任务', 'number', 'agency', '年度销售任务金额', 0, 83, 1),
('quarterlyTask', '季度任务', 'Quarterly Target', '季度任务', 'number', 'agency', '季度销售任务金额', 0, 84, 1),
('consecutiveQuarters', '连续季度数', 'Consecutive Quarters', '连续季度数', 'number', 'agency', '考核连续未完成季度数', 0, 85, 1),
('taskPercentage', '任务完成比例', 'Task Completion (%)', '任务完成比例', 'number', 'agency', '任务完成比例阈值（%）', 0, 86, 1),
('minRetailPrice', '最低零售价', 'Minimum Retail Price', '最低零售价', 'number', 'agency', '最低零售价格', 0, 87, 1),
('priceNoticeDays', '价格调整通知天数', 'Price Change Notice (Days)', '价格调整通知天数', 'number', 'agency', '价格调整提前通知天数', 0, 88, 1),
('commissionRate', '佣金比例', 'Commission Rate (%)', '佣金比例', 'number', 'agency', '佣金比例（%）', 0, 89, 1),
('salesTarget1', '销售目标1', 'Sales Target 1', '销售目标1', 'number', 'agency', '返利档位销售额1（万）', 0, 90, 1),
('rebateRate1', '返利比例1', 'Rebate Rate 1 (%)', '返利比例1', 'number', 'agency', '档位1返利比例（%）', 0, 91, 1),
('salesTarget2', '销售目标2', 'Sales Target 2', '销售目标2', 'number', 'agency', '返利档位销售额2（万）', 0, 92, 1),
('rebateRate2', '返利比例2', 'Rebate Rate 2 (%)', '返利比例2', 'number', 'agency', '档位2返利比例（%）', 0, 93, 1),
('samplesCount', '样品套数', 'Sample Sets', '样品数量', 'number', 'agency', '市场支持样品套数', 0, 94, 1),
('promoMaterialsCount', '宣传物料份数', 'Promo Materials (Copies)', '宣传物料数量', 'number', 'agency', '宣传物料份数', 0, 95, 1),
('adSupportAmount', '广告支持金额', 'Ad Support Amount', '广告支持金额', 'number', 'agency', '广告支持金额（元）', 0, 96, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_en = VALUES(name_en),
  label = VALUES(label),
  type = VALUES(type),
  category = VALUES(category),
  description = VALUES(description),
  required = VALUES(required),
  sort_order = VALUES(sort_order),
  status = VALUES(status);

-- 模板变量分类：代理/渠道（与前端筛选一致）
INSERT IGNORE INTO quick_code_item (header_id, code, meaning, meaning_en, description, description_en, tag, enabled, sort_order)
SELECT h.id, 'agency', '代理/渠道', 'Agency / Channel', '销售代理、经销相关变量', 'Sales agency and distribution variables', 'variable-category', true, 8
FROM quick_code_header h WHERE h.code = 'TEMPLATE_VARIABLE_CATEGORY' LIMIT 1;

UPDATE quick_code_item i
INNER JOIN quick_code_header h ON i.header_id = h.id
SET i.sort_order = 9
WHERE h.code = 'TEMPLATE_VARIABLE_CATEGORY' AND i.code = 'custom';
